-- CREATE

create table department (
                            id              SERIAL        NOT NULL PRIMARY KEY,
                            city            varchar(255)  NOT NULL,
                            district        varchar(255)  NOT NULL,
                            address         varchar(255)  NOT NULL,
                            phone_number    varchar(255)  NOT NULL
);

CREATE TABLE patient (
                         id              BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         birthdate       DATE          NOT NULL,
                         gender          VARCHAR(15)   NOT NULL,
                         chi_policy      VARCHAR(255)  NOT NULL,
                         passport        VARCHAR(15)   NOT NULL,
                         phone_number    VARCHAR(15)   NOT NULL,
                         password        VARCHAR(255)  NOT NULL
);

create table schedule (
                        id                BIGINT       PRIMARY KEY,
                        doctor_id         BIGINT       NOT NULL REFERENCES doctor(id) on DELETE cascade ON UPDATE CASCADE,
                        department_id     BIGINT       NOT NULL REFERENCES department(id) on DELETE cascade ON UPDATE CASCADE,
                        date              DATE         NOT NULL,
                        start_time        TIME         NOT NULL,
                        end_time          TIME         NOT NULL CHECK( end_time > start_time ),
                        cabinet           INT          NOT NULL CHECK( cabinet > 0 ),
                        is_available      BOOLEAN      NOT NULL
);

CREATE TABLE appointment (
                        id                BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        patient_id        BIGINT       NOT NULL REFERENCES patient(id) on DELETE cascade ON UPDATE CASCADE,
                        doctor_id         BIGINT       NOT NULL REFERENCES doctor(id) on DELETE cascade ON UPDATE CASCADE,
                        date              TIMESTAMP    NOT NULL
);

-- INSERT

INSERT INTO department(city, district, address, phone_number)
VALUES ('Москва', 'Центральный', 'Красная площадь 15', '+78005553535'),
       ('Санкт-Петербург', 'Калининский', 'Чекистов 28', '+78005553536'),
       ('Волгоград', 'Южный', 'Чапаева 15', '+78005553537'),
       ('Смоленск', 'Октябрьский', 'Кирпичная 25', '+78005553538'),
       ('Сочи', 'Северный', 'Столичная 55', '+78005553539');







