CREATE TABLE IF NOT EXISTS appointment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT,
    FOREIGN KEY (patient_id) REFERENCES patient (Id),
    doctor_id  BIGINT,
    FOREIGN KEY (doctor_id) REFERENCES doctor (Id),
    date       TIMESTAMPTZ NOT NULL,
    timestamp  TIMESTAMPTZ NOT NULL
);
