CREATE TABLE IF NOT EXISTS appointment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
                       PRIMARY KEY,
    patient_id  BIGINT,
    FOREIGN KEY (Patient_id) REFERENCES Patient(Id),
    doctor_id  BIGINT,
    FOREIGN KEY (Doctor_id) REFERENCES Doctor(Id),
    date        TIMESTAMPTZ NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL
    );
